//Priorities:
//Check copying issue on Facebook's browser. <- Permissions issue?
//Add error message for copying. <- Check somehow.
//Shrink modal stuff on small screens. - done?
//on the first play. Say to click the question mark for more details.
//Fix incorrect guessNumber display on reload the next day.
//copiedAlert sometimes shows under other things for some reason?
//Play button on fail fucked up on sideways layouts - not taking extra height for both words.

//Short-term goals:
//Update var to let in other files
//Study and check changing mobile keyboard button to Enter
//Slice .js pages so that identical script is shared. - If possible.
//Add settings option to hide stringsList.
//Alpha testing.

//Super stretchy goals:
//Really stretchy goal: add user stats/streaks (more cookies/local storage).
//Consider Ian's idea of giving hints based on the letters in the user's guess.
//Add archived games to play (calendar icon). -> DB? Or add it to Python cron script? Open old values.js,
//read and copy data to a file with a name including the autogenerated date, save that file to archives
//directory, run the current script on the main values.js
//For archived games: add option under +? Then let the user scroll through a list of dates which would have
//to be autogenerated each day as well (added from cron job?) and possibly saved as objects
//(let d20230926 = {goalNumber: 18, letterValues: {"A": 6, "B", 3, etc.}}) Collect d20230926.goalNumber, etc.
//Therefore, cron job needs to handle: todaysDate variable, goalNumber, letterValues. Call todaysDate from
//archives option at the end of the + list. Each archives page needs to call the associated values for that date.
//Archives list visible to the user must have dates converted into a readable format..
//Rewrite Help to be shorter and snappier.
//Make text sized more appropriately to different screens.



